# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
# https://prefix-dev.github.io/rattler-build/latest/recipe_file/
context: {}
package:
  name: minetest-gymnasium
  version: "0.29"

source:
  path: ../../

build:
  number: 0
  script: python -m pip install ./minetest-gymnasium -v
  noarch: python


requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - minetest =0.22
    # python deps
    - gymnasium
    - numpy =1.26
    - pycapnp >=2,<3

about:
  repository: https://github.com/Astera-org/minetest
  summary: 'Minetest gymnasium interface'

tests:
  - python:
      imports:
        - minetest
  - script:
    # Install the devtest game, which is needed for python test.
    - mkdir ${CONDA_PREFIX}/share/minetest/games
    - ln -s -t ${CONDA_PREFIX}/share/minetest/games ${PWD}/games/devtest
    - if [[ $(minetest --gameid list) != "devtest" ]]; then exit 1; fi
    - cd minetest-gymnasium && pytest --timeout=60 -v . || (cat /tmp/*/log/*stderr* && exit 1)
    files:
      source:
        - games/devtest/
        - minetest-gymnasium/tests/
        - minetest-gymnasium/pyproject.toml
    requirements:
      run:
        - pillow
        - pytest
        - pytest-timeout
