name: android

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Build APKs with Gradle
      run: cd android; ./gradlew assembleDebug
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-armeabi-v7a.apk
        path: android/app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-arm64-v8a.apk
        path: android/app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
    - name: Save x86 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-x86.apk
        path: android/app/build/outputs/apk/debug/app-x86-debug.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: Luanti-x86_64.apk
        path: android/app/build/outputs/apk/debug/app-x86_64-debug.apk
